### ISSUE TITLE
Ordering of js_files not preserved

### ISSUE THREAD

**Issue by shiftdirector** [noirbizarre/django.js#17]
When passing an array of files to the js_file parameter of views JasminView or QUnitView, the ordering is changed by StorageGlobber.glob(). Example below.

ps. Django.js is awesome, big thank you.

In [2]: from djangojs.utils import StorageGlobber
In [3]: js_files=[
   ...:                                 'js/libs/underscore/underscore-min.js',
   ...:                                 'js/libs/backbone/backbone-min.js',
   ...:                                 'js/backbone.models.js',
   ...:                                 'js/tests/*.tests.js',
   ...:                             ]

In [4]: StorageGlobber.glob(js_files)
Out[4]: 
[u'js/backbone.models.js',
 u'js/libs/backbone/backbone-min.js',
 u'js/libs/underscore/underscore-min.js',
 u'js/tests/something.tests.js']

**Comment by noirbizarre** [comment]
Thanks for the reports (and for the compliment).

If you don't mind, I have some other features and fixes to integrate before performing a release but I release it soon.
