### ISSUE TITLE
Django.js is incompatible with custom user model

### ISSUE THREAD

**Issue by thepapermen** [noirbizarre/django.js#18]
Hi! Thanks for `eztables` and `django.js`! :))

Please support [custom user model](https://docs.djangoproject.com/en/dev/topics/auth/customizing/#specifying-a-custom-user-model).

Here's a nice fork where the issue is fixed:
https://github.com/larssos/django.js/tree/custom-user-model

Steps to reproduce bug: install custom user model, authenticate user and watch django.js fail to load.

Good luck!
Best regards,
Ivan

**Comment by noirbizarre** [comment]
Thanks.

I added a test case and fixed it (using the same way than in your fork).
