### ISSUE TITLE
Django.url can't handle optional trailing slash in URL regex

### ISSUE THREAD

**Issue by rouge8** [noirbizarre/django.js#20]
When a URL pattern has an optional trailing slash, `_get_urls()` matches the URL as `url/?` rather than `url`.

I pushed a failing test case in d78a14042ee40c424196ac5ba617b15c88255ca5. I'm going to take a look at it in more detail later, but it didn't appear to be a trivial fix.

**Comment by rouge8** [comment]
Looks like that was easier than I thought. Thanks for the quick fix!

**Comment by noirbizarre** [comment]
Regex power !!!

You're welcome !
By the way, thanks for the reports and the many contributions !
