### ISSUE TITLE
django.js seems incompatible with social_auth

### ISSUE THREAD

**Issue by Karmak23** [noirbizarre/django.js#21]
Hi,

when using any of the django `social_auth` templates context processors, the `django.js` **init.js** view fails because it can't serialize the request context to JSON. That's because `social_auth` installs one or more `LazyDict` in it, instead of a plain `dict()`, and the default `JSONEncoder` doesn't know how to serialize a lazy dict.

You've got the full stack trace here: 

http://dev.1flow.net/development/1flow-dev/group/448/

I'd like an advise or at least your point of view on this issue:
- Is it really needed to serialize all the context in `{% django_js_init %}` ? I currently don't use the serialized context in any way. It would be interesting in this case to be able to disable context serialization in settings, for example. This would make us gain a few cpu cycles.
- or perhaps a more granular approach: provide a list of context variables that will not be serialized at all. This could be also from a setting, like `DJANGO_JS_CONTEXT_IGNORE=['social_auth', … ]`. This would make some things not available client side, but it's a bad for a good.
- or even more granular: to be able to provide my own serializers from settings, eg `DJANGO_JS_CONTEXT_PROCESSORS=['myapp.context_serializers.process_social_auth']`, that would be looked up the same way as `django.js` already does today, (eg. `if hasattr(cls, 'process_%s' % key) …` ). This would allow me to provide the processors _cleanly_, without having to monkey patch `djangojs.utils.ContextSerializer`, which should work perfectly but is kind of rough and not friendly.

What would be your prefered approach ? I personaly prefer the third, and if you agree I can try to write a clean patch for `django.js`. In the patch, I could include my `social_auth` serializer (which will obviously just dump the `LazyDict` as a standard `dict()`) which could eventually be enabled by default, given the fact that `social_auth` is kind of common nowadays. Adding the second approach as an alternative seems easy, too. I can implement both. 

Anyway, your feedback on this issue will be appreciated. I didn't study enough `django.js` to know if the first approach (completely disabling serialization) makes sense, or not.

best regards,

**Comment by noirbizarre** [comment]
Hi!

You're proposal is very interesting!
I'm thinking in implementing the 3 solutions because they cover 3 differents use cases:
- provide a `JS_CONTEXT_ENABLED` that defaults to True (and the same for `JS_URLS_ENABLED` and `JS_USER_ENABLED`) allowing to disable features on demand.
- provide both white and black lists for context variable, the same way I have a black and white list for urls (should be `JS_CONTEXT` and `JS_CONTEXT_EXCLUDE` to follow th same pattern).
- provide a `JS_CONTEXT_PROCESSORS` allowing users to customize `Django.js` behavior.

Concerning the specific case of `social_auth`, having a standard way of handling `LazyDict` can maybe solve other compatibility issues.

Don't hesitate to provide a pull-request handling it.
You can look into the test suite to see what's currently handled and how it's handled.
Use `tox` to see if it's compatible with both Python 2 and 3 (I should add a contribute age to the documentation)

Thanks by the way for the interesting report !

**Comment by Karmak23** [comment]
I can see that you implement all 3 points by yourself faster than I could have done. 
That's very nice !! I reviewed your code an asides a harmless typo, it should do exactly what I need.
I will test it with a custom serializer for social_auth tomorrow during my work journey.
Best regards,

**Comment by Karmak23** [comment]
Hello again,

I've not yet tested everything because I'm still in the social_auth setup phase, but currently everything works ok with your latest code and this one on my side:

Settings:

```
JS_CONTEXT_PROCESSOR = 'oneflow.base.utils.JsContextSerializer'
```

```
class JsContextSerializer(ContextSerializer):
    """ This class should probably move into sparks some day. """

    def process_social_auth(self, social_auth, data):
        """ Just force social_auth's LazyDict to be converted to a dict for the
            JSON serialization to work properly. """

        data['social_auth'] = dict(six.iteritems(social_auth))

    def handle_user(self, data):
        """ We just add the user ID to everything already gathered by Django.JS
            user serializer. """

        super(JsContextSerializer, self).handle_user(data)

        data['user']['id'] = self.request.user.id
```

Note that I extended `handle_user()` to have the `user_id`. Perhaps this could go directly into `django.js`, because I use the ID to retreive the user via tastypie, I find it more direct than looking it up via the username.

I'll keep updates when I go farther.
Best regards,

**Comment by noirbizarre** [comment]
OK, I'l wait for your code for `social_auth` support before releasing.

I need to to some refactoring by my side, maybe integrate the dictionnary casting directly into the base `ContextProcessor`.

For user support, I was planning to allow custom extra user attributes but the custom `ContextProcessor` do the work just fine.

I'm going document it a little bit more and maybe I'll ask you some testing.

I'll keep looking for your updates.

See Ya

**Comment by Karmak23** [comment]
Re,

the custom "obvious" dict() casting doesn't work "as is". In its current form, `DJANGO_JS_CONTEXT['social_auth']` is always `null` on the client side. It needs more love because the internal structure of the `social_auth` context variable can be either a dict(), or a list() of dicts (cf. http://django-social-auth.readthedocs.org/en/v0.7.22/configuration.html#template-context-processors). 

Too bad. I've been doing other things after having noticed the fail, and I've just understood the "why" now. I will give it another pass tomorrow. It should be easy to implement a `social_auth`-only handler. I'm not yet in the mood of subclassing the JSONEncoder to catch `LazyDict` in a more generic way. This should be the clean way to go, but anyway `LazyDict` is a `social_auth`-only structure, so it won't help other projects to re-implement the JSONEncoder.

I'll let the night decide which implementation I choose and will keep you posted. Don't hesitate to ask for testing. I'll try to find the time to do it.

Regards,

**Comment by noirbizarre** [comment]
Hello,

Any advancements ?

I was thinking in creating a `djangojs.contrib` package to host contibuted special processors.
So if yours is working, why not submit in a pull-request as `djangojs.contrib.social_auth` so everybody can use your work by simply setting:

``` python
JS_CONTEXT_PROCESSOR = djangojs.contrib.social_auth.ContextSerializer
```

The must would be to have `djangojs/contrib/social_auth.py` with both a mixin and a ContextSerializer:

``` python
from djangojs.utils import ContextSerializer as BaseContextSerializer

class SocialAuthMixin(object):
    def process_social_auth(self, social_auth, data):
        """Just force social_auth's LazyDict to be converted to a dict for the JSON serialization to work properly."""
        # Do some magic


class ContextSerializer(SocialAuthMixin, BaseContextSerializer):
    pass
```

This way, developpers can create their own custom serializer combining mixins like this:

``` python
class MySerializer(SocialAuthMixin, AnotherMixin, ContextSerializer):
    def process_custom(self, value, data):
        # Some custom magic
```

**Comment by Karmak23** [comment]
Hi,

Sorry for delay. I couldn't work on this side. probably tomorrow.

I don't mind using a contrib directory. This would be cool to already have already-packed serializers.

regards,
Olivier

PS: I close the issue because whatever my serializer does, you already commited all the needed parts for me to be unblocked. thanks !!

**Comment by noirbizarre** [comment]
You're welcome!

I created the contrib package and I'm waiting for your pull-request adding the `djangojs.contrib.social_auth` module for the next release.
