### ISSUE TITLE
Support script prefix (subpaths)

### ISSUE THREAD

**Issue by ebrelsford** [noirbizarre/django.js#34]
It would be great if the URLs in `init.js` could be prefixed by the `SCRIPT_NAME` header, which facilitates running projects on a subpath (eg http://example.com/myproject/).

Otherwise it looks like you have to manually add the prefix. Or is there a better way I'm not seeing?

Any guidance on doing this? Would be glad to give it a shot.

**Comment by randlet** [comment]
@ebrelsford  can you see if [this pull request](https://github.com/noirbizarre/django.js/pull/38) fixes the issue for you?

**Comment by ebrelsford** [comment]
Sorry for getting back so late--just tried it (as merged into master) and it works like a charm! Thanks @randlet!

**Comment by randlet** [comment]
No problem. Glad to hear it worked for you  :)
