### ISSUE TITLE
Django 1.3 support?

### ISSUE THREAD

**Issue by ikresoft** [noirbizarre/django.js#6]
I am not able to use it in django projects version 1.3.

**Comment by noirbizarre** [comment]
I must admit it was not intended to run on django 1.3.
It was primarily designed for django 1.4 and aim to be ready for the 1.5 release.

However, I will try it on Django 1.3.
Can you give some more details: what is failing ?

**Comment by ikresoft** [comment]
can't find patterns, url, include
- I fix it with adding default module to import
  then problem is in conf.py
  self.update(settings._wrapped.__dict__)
  _wrapped is None
  and I cant fix this.

but anyway if your plans are not involving django 1.3, I will migrate my projects to 1.4, then I will try.

**Comment by noirbizarre** [comment]
OK.
I'm closing this issue then.

Don't hesitate if you have some troubles with django.js after your 1.4 upgrade.

**Comment by ikresoft** [comment]
I have a problem:
uncaught exception: URL for view "admin:studentska_sluzba_zapisnik_change" not found

how can I check for url list in javascript. Its look like admin urls are not in url list. I cant figure out why is not working

**Comment by noirbizarre** [comment]
If you have in you root urls.py:

``` python
url(r'^djangojs/', include('djangojs.urls')),
```

then you can access the generated JSON here: `/djangojs/urls`

I didn't test namespaced urls and dynamic urls so as soon as you have more details, please submit another issue.
I will investigate ASAP.

**Comment by noirbizarre** [comment]
I added support for namespaced URLs in 9e54f84668b
You should check if it's working now.
